version: "3"
services:
  ff_back:
    image: ff_back
    build: ./
    environment: 
      - PORT=3000
    ports:
      - 3000:3000
    depends_on:
      - mongo
  
  mongo:
    image: mongo

  redis:
    image: redis

volumes:
  mongo-db:  
    
